# accounts/models.py

from django.db import models

class Company(models.Model):
    """
    Fields:
    - id (PK): Automatically generated by Django.
    - name: Unique identifier for the company.
    - description: Optional additional information about the company.
    - created_at: Timestamp for creation, automatically set.
    - updated_at: Timestamp for last update, automatically updated.

    Relationships:
    - Many-to-One (as 'Company' side): Linked by Employee, JobPosting, Candidate, Application models.
      (e.g., An Employee belongs to ONE Company, but a Company can have MANY Employees).
    """
    name = models.CharField(max_length=255, unique=True, db_index=True, help_text="Name of the company (must be unique).") # db_index added for performance
    description = models.TextField(blank=True, null=True, help_text="A brief description of the company.")
    created_at = models.DateTimeField(auto_now_add=True, help_text="The date and time when the company record was created.")
    updated_at = models.DateTimeField(auto_now=True, help_text="The date and time when the company record was last updated.")

    class Meta:       
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        ordering = ['name'] # Orders companies alphabetically by name

    def __str__(self):
        return self.name