# Generated by Django 5.2.3 on 2025-07-01 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the employee record was created.')),
                ('company', models.ForeignKey(help_text='The company this HR employee is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='hr_employees', to='accounts.company')),
                ('user', models.OneToOneField(help_text='The associated user account for this HR employee.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Employee',
                'verbose_name_plural': 'HR Employees',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Candidate's first name.", max_length=100)),
                ('last_name', models.CharField(help_text="Candidate's last name.", max_length=100)),
                ('email', models.EmailField(db_index=True, help_text="Candidate's unique email address.", max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('resume', models.FileField(blank=True, help_text="Candidate's resume file (PDF only).", null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the candidate record was created.')),
                ('company', models.ForeignKey(help_text='The company this candidate is applying to or associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The HR Employee who created this candidate record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to='portal.employee')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the job posting.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the job.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the job posting was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the job posting was last updated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the job posting is currently active.')),
                ('auto_title_generated', models.BooleanField(default=False, help_text='Was the title generated by AI?')),
                ('company', models.ForeignKey(help_text='The company that posted this job.', on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The HR Employee who created this job posting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_postings', to='portal.employee')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the application was submitted.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Interviewed', 'Interviewed'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], db_index=True, default='Pending', help_text='Current status of the application (e.g., Pending, Reviewed, Interviewed, Rejected, Hired).', max_length=50)),
                ('candidate', models.ForeignKey(help_text='The candidate who submitted this application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.candidate')),
                ('job_posting', models.ForeignKey(help_text='The job posting this application is for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.jobposting')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job_posting'), name='unique_application_for_job')],
            },
        ),
    ]
