# Generated by Django 5.2.3 on 2025-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the company (must be unique).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the company.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the company record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the company record was last updated.')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
